# Generated by Django 3.0.3 on 2020-06-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_news_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created_by',
        ),
    ]
