# Generated by Django 3.0.3 on 2020-06-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0009_news_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='create_adate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='create_adate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='create_adate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
